permalink: /:categories:month/:title
markdown: rdiscount
rdiscount:
  extensions: [smart]
pygments: true
url: http://emineker.net
exclude:
        - Rakefile
        - Makefile
        - presentation.md
        - presentation.html
        - presentation.png
        - media

account: emineker
archive: Son Girdiler
assets: /assets
author: Emin Eker
disqus: emineker
email: emineker@bil.omu.edu.tr
facebook: ~
feed: ~
flickr: ~
google: ~
domain: emineker.net
googleanalyticsid: UA-40135421-1
googleplus: 110754783365796157780
gpg: ~
homeurl: http://emineker.net
logo: /assets/19/19-normal-128x128.png
organization: 19
picasa: ~
related: Diğer Girdiler
repository: emineker.github.com
ribbon: GitHub'dayım
title: Emin Eker
twitter: http://twitter.com/emineker

navigator:
        0: Teknik Olmayan Yazılar
        1: Teknik Yazılar
        9: Kısa Notlar
